[[connections]]
name                   = "root@fjail/fuserdata"           # human readable, show in explorer
user                   = "root"
host                   = "192.168.31.11"
port                   = "22"                             # string, not number
folder                 = "/media/fuserdata"               # which folder to mount
mountPoint             = "X:"                             # make sure this drive letter is availble
identityFile           = "C:/Users/Fifv/.ssh/id_ed255519" # only support public key, can't use password
isMountAsANetworkDrive = true

[[connections]]
name                   = "root@fjail/BitTorrentDownload/"
user                   = "root"
host                   = "192.168.31.11"
port                   = "22"
folder                 = "/media/BitTorrentDownload/"
mountPoint             = "Y:"
identityFile           = "C:/Users/Fifv/.ssh/id_ed255519"
isMountAsANetworkDrive = true

[[connections]]
name                   = "root@fjail"
user                   = "root"
host                   = "192.168.31.11"
port                   = "22"
folder                 = "/"
mountPoint             = "Z:"
identityFile           = "C:/Users/Fifv/.ssh/id_ed255519"
isMountAsANetworkDrive = true

[[connections]]
name                   = "fifv@VB.Arch/"
user                   = "fifv"
host                   = "192.168.56.102"
port                   = "22"
folder                 = "/"
mountPoint             = "R:"
identityFile           = "C:/Users/Fifv/.ssh/id_ed255519"
isMountAsANetworkDrive = false
